# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  	config.vm.box = "ubuntu_15.04_160715"
	config.vm.network "private_network", ip: "172.28.128.9"
	config.vm.host_name = "owncloud"
	config.vm.synced_folder "vagrant", "/vagrant", disabled: true

	config.vm.provision "shell", path: "./provision.sh"

	config.vm.provider "virtualbox" do |vb|
   		vb.memory = "1024"
  	end

	config.vm.synced_folder "./puppet/modules", "/etc/puppet/modules"
	config.vm.synced_folder "./puppet/manifests", "/etc/puppet/manifests"	
	config.vm.provision "puppet" do |puppet|
		puppet.options = "--verbose --debug"
		puppet.module_path = "puppet/modules"
		puppet.manifests_path = "puppet/manifests"
		puppet.manifest_file = "default.pp"
	end

end
