# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

	config.vm.box = "ubuntu/trusty64"
	#config.vm.network "public_network", bridge: "your-bridge", ip: "0.0.0.0"
	config.vm.network "private_network", ip: "172.28.128.11"


	config.vm.provider "virtualbox" do |vb|
  		vb.memory = "2048"
 	end


	config.vm.define :ntp1 do |ntp1|
    		ntp1.vm.hostname = "ntp1"
	end

	config.vm.synced_folder "./puppet/", "/etc/puppet/"



	config.vm.provision :puppet, :options => ["--yamldir /etc/puppet/hiera"]  do |puppet|
		puppet.manifests_path = "puppet/manifests"
		puppet.module_path = "puppet/modules"
		puppet.manifest_file = "site.pp"
		puppet.environment = "dev"
		puppet.hiera_config_path = "puppet/hiera.yaml"
		puppet.options = "--verbose --debug"
	end


end
