# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  	config.vm.box = "ubuntu/xenial64"
	config.vm.hostname = "jenkins"
	config.vm.network :private_network, ip: "192.168.0.1"
	config.vm.provision "shell", path: "./provision.sh"
	config.vm.synced_folder "vagrant", "/vagrant", disabled: true
	config.vm.provider "virtualbox" do |vb|
   		vb.memory = "2048"
  	end
end
